## **K Nearest Neighbour Classifier**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
from sklearn.datasets import make_classification
X,y = make_classification(
    n_samples=1000,
    n_classes=2,
    n_features=3,
    n_redundant=1,
    random_state=999
    )

In [5]:
X

array([[-0.33504974,  0.02852654,  1.16193084],
       [-1.37746253, -0.4058213 ,  0.44359618],
       [-1.04520026, -0.72334759, -3.10470423],
       ...,
       [-0.75602574, -0.51816111, -2.20382324],
       [ 0.56066316, -0.07335845, -2.15660348],
       [-1.87521902, -1.11380394, -4.04620773]])

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [8]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5,algorithm='auto')
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [9]:
y_pred = classifier.predict(X_test)

In [10]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[158  11]
 [ 20 141]]
              precision    recall  f1-score   support

           0       0.89      0.93      0.91       169
           1       0.93      0.88      0.90       161

    accuracy                           0.91       330
   macro avg       0.91      0.91      0.91       330
weighted avg       0.91      0.91      0.91       330



In [11]:
# Applying Grid Search CV
from sklearn.model_selection import GridSearchCV
param_grid = {'n_neighbors':np.arange(1,50)}
grid = GridSearchCV(estimator=classifier,param_grid=param_grid,cv=5,n_jobs=-1)
grid.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])})

In [12]:
y_pred1 = grid.predict(X_test)

In [14]:
grid.best_params_

{'n_neighbors': np.int64(9)}

In [13]:
print(confusion_matrix(y_test,y_pred1))
print(classification_report(y_test,y_pred1))

[[156  13]
 [ 16 145]]
              precision    recall  f1-score   support

           0       0.91      0.92      0.91       169
           1       0.92      0.90      0.91       161

    accuracy                           0.91       330
   macro avg       0.91      0.91      0.91       330
weighted avg       0.91      0.91      0.91       330



## **K Nearest Neighbour Regressor**

In [16]:
from sklearn.datasets import make_regression
X,y = make_regression(
    n_samples=1000,
    n_features=2,
    noise=10,
    random_state=42
)


In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [20]:
from sklearn.neighbors import KNeighborsRegressor
regressor = KNeighborsRegressor(n_neighbors=5,algorithm='auto')
regressor.fit(X_train,y_train)

KNeighborsRegressor()

In [22]:
y_pred2 = regressor.predict(X_test)

In [27]:
from sklearn.metrics import mean_absolute_error,r2_score
print(r2_score(y_test,y_pred2))
print(mean_absolute_error(y_test,y_pred2))


0.9155927746462499
9.269174435861805


In [28]:
from sklearn.model_selection import GridSearchCV
param_grid = {'n_neighbors':np.arange(1,50)}
grid = GridSearchCV(estimator=regressor,param_grid=param_grid,cv=5,n_jobs=-1)
grid.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsRegressor(), n_jobs=-1,
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])})

In [29]:
grid.best_params_

{'n_neighbors': np.int64(7)}

In [30]:
y_pred3 = grid.predict(X_test)

In [31]:
from sklearn.metrics import mean_absolute_error,r2_score
print(r2_score(y_test,y_pred3))
print(mean_absolute_error(y_test,y_pred3))

0.9190743939278913
8.949111514931198
